version: '3'
services:
  web:
    build: .
    volumes:
      - ./todo:/todo
    command: php artisan serve --host 0.0.0.0 --port 8081
    ports:
      - 8081:8081
  db:
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
    volumes:
      - todo-db:/var/lib/postgresql/data
    ports:
      - 5434:5432
volumes:
  todo-db:
